=== KostayUa/data-exchange-format/purchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/purchaseOrder"
           xmlns="http://www.example.org/purchaseOrder"
           elementFormDefault="qualified">
    <xs:element name="purchaseOrder">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company" type="companyType" maxOccurs="unbounded"/>
                <xs:element name="date" type="xs:date"/>
                <xs:element name="number" type="xs:integer"/>
                <xs:element name="vendor" type="vendorType" maxOccurs="unbounded"/>
                <xs:element name="shipTo" type="shipToType" maxOccurs="unbounded"/>
                <xs:element name="currency" type="xs:string"/>
                <xs:element name="productLines" type="productLinesType"/>
                <xs:element name="subtotal" type="xs:decimal"/>
                <xs:element name="tax" type="xs:decimal" minOccurs="0"/>
                <xs:element name="shipping" type="xs:decimal" minOccurs="0" nillable="true"/>
                <xs:element name="other" type="xs:decimal" minOccurs="0" nillable="true"/>
                <xs:element name="total" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="companyType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="cityStZip" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="fax" type="xs:string"/>
            <xs:element name="website" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vendorType">
        <xs:sequence>
            <xs:element name="companyName" type="xs:string"/>
            <xs:element name="department" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="cityStZip" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="fax" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="shipToType">
        <xs:sequence>
            <xs:element name="companyName" type="xs:string"/>
            <xs:element name="recipient" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="cityStZip" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productLinesType">
        <xs:sequence>
            <xs:element name="productLine" type="productLineType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productLineType">
        <xs:sequence>
            <xs:element name="code" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="quantity">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute name="unit" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="price" type="xs:decimal"/>
            <xs:element name="total" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== KostayUa/data-exchange-format/purchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseOrder xmlns="http://www.example.org/purchaseOrder"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.example.org/purchaseOrder purchaseOrder.xsd">
    <company>
        <name>Delivery of future</name>
        <address>Soborna av.32</address>
        <cityStZip>Ir41400</cityStZip>
        <phone>(093) 439-0011</phone>
        <fax>(050) 332-8734</fax>
        <website>https://delivery.com</website>
    </company>
    <date>2024-10-02</date>
    <number>4515</number>
    <vendor>
        <companyName>SavBut</companyName>
        <department>storage</department>
        <address>Soborna av.88</address>
        <cityStZip>Ir41400</cityStZip>
        <phone>(050) 88-9999</phone>
        <fax>(097) 35-5593</fax>
    </vendor>
    <shipTo>
        <companyName>private person</companyName>
        <recipient>address delivery</recipient>
        <address>Obolon 32</address>
        <cityStZip>Kv53354</cityStZip>
        <phone>(050) 09-1492</phone>
    </shipTo>
    <currency>USD</currency>
    <productLines>
        <productLine>
            <code>123123</code>
            <description>ProductABC</description>
            <quantity unit="pcs">50</quantity>
            <price>10.00</price>
            <total>500.00</total>
        </productLine>
        <productLine>
            <code>456456</code>
            <description>ProductLMNO</description>
            <quantity unit="pcs">1</quantity>
            <price>250.00</price>
            <total>250.00</total>
        </productLine>
        <productLine>
            <code>789789</code>
            <description>ProductXYZ</description>
            <quantity unit="doz">15</quantity>
            <price>6.00</price>
            <total>90.00</total>
        </productLine>
    </productLines>
    <subtotal>840.00</subtotal>
    <tax>0.00</tax>
    <shipping>0.00</shipping>
    <other>0.00</other>
    <total>840.00</total>
</purchaseOrder>
